version: '3.9'
services:
  mongo-express:
    image: mongo
    container_name: beskydmongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db